name: BasicWebAPI CI/CD

on:
  push:
    branches: [dev, qa, main]
    paths:
      - 'BasicWebAPI/**'

permissions:
  contents: write

jobs:

  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: BasicWebAPI/BasicWebAPI

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:

    - name: Checkout Code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'

    - name: Generate Version
      id: version
      run: |
        VERSION=1.0.${{ github.run_number }}
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Restore
      run: dotnet restore BasicWebAPI.sln

    - name: Build
      run: dotnet build BasicWebAPI.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ../BasicWebAPI.Test/BasicWebAPI.Test.csproj --no-build

    - name: Publish API
      run: dotnet publish BasicWebAPI.csproj -c Release -o ${{ github.workspace }}/publish

    - name: Show Publish Folder
      run: ls -R ${{ github.workspace }}/publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: basicwebapi-${{ steps.version.outputs.version }}
        path: ${{ github.workspace }}/publish

  deploy-dev:

    needs: build
    if: github.ref == 'refs/heads/dev'

    runs-on: ubuntu-latest
    environment: dev

    steps:

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: basicwebapi-${{ needs.build.outputs.version }}
        path: publish

    - name: Deploy to Dev
      run: |
        echo "Deploying to DEV server"
        ls -R publish


  deploy-qa:

    needs: build
    if: github.ref == 'refs/heads/qa'

    runs-on: ubuntu-latest
    environment: qa

    steps:

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: basicwebapi-${{ needs.build.outputs.version }}
        path: publish

    - name: Deploy to QA
      run: |
        echo "Deploying to QA server"
        ls -R publish


  deploy-production:

    needs: build
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    environment: production

    steps:

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: basicwebapi-${{ needs.build.outputs.version }}
        path: publish

    - name: Deploy to Production
      run: |
        echo "Deploying to Production server"
        ls -R publish

    - name: Create Git Tag
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        TAG=v${{ needs.build.outputs.version }}
        git tag $TAG
        git push origin $TAG