name: Build VB .NET Desktop App

# Force Node.js 24 for all JS-based actions
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main
    paths:
      - 'BasicWindowsFormsApp/**'
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        working-directory: BasicWindowsFormsApp
        run: nuget restore BasicWindowsFormsApp.sln

      - name: Build solution
        working-directory: BasicWindowsFormsApp
        run: msbuild BasicWindowsFormsApp.sln /p:Configuration=Release

      - name: Publish output
        run: |
         mkdir publish
         robocopy BasicWindowsFormsApp\bin\Release publish /E || exit 0


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: desktop-app
          path: publish